layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  medium: linnefromice
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: WORK

  - name: React
    web_url: https://reactjs.org/
    image_url: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii0xMS41IC0xMC4yMzE3NCAyMyAyMC40NjM0OCI+CiAgPHRpdGxlPlJlYWN0IExvZ288L3RpdGxlPgogIDxjaXJjbGUgY3g9IjAiIGN5PSIwIiByPSIyLjA1IiBmaWxsPSIjNjFkYWZiIi8+CiAgPGcgc3Ryb2tlPSIjNjFkYWZiIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIi8+CiAgICA8ZWxsaXBzZSByeD0iMTEiIHJ5PSI0LjIiIHRyYW5zZm9ybT0icm90YXRlKDYwKSIvPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIiB0cmFuc2Zvcm09InJvdGF0ZSgxMjApIi8+CiAgPC9nPgo8L3N2Zz4K
  - name: Vue
    web_url: https://vuejs.org/
    image_url: https://vuejs.org/images/logo.png
  - name: Spring Boot
    web_url: https://spring.io/projects/spring-boot
    image_url: https://spring.io/img/homepage/icon-spring-boot.svg
  - name: Oracle
    web_url: https://www.oracle.com/index.html
    image_url: https://seeklogo.com/images/O/Oracle-logo-430F2F9F33-seeklogo.com.png
  - name: Docker
    web_url: https://www.docker.com/
    image_url: https://www.docker.com/sites/default/files/d8/styles/role_icon/public/2019-07/Docker-Logo-White-RGB_Moby.png

  - name: PRIVATE
  
  - name: Flutter
    web_url: https://flutter.dev/
    image_url: https://cdn.worldvectorlogo.com/logos/flutter-logo.svg
  - name: Expo
    web_url: https://expo.io/
    image_url: https://d30j33t1r58ioz.cloudfront.net/static/brand/square-512x512.png
  - name: Firebase
    web_url: https://firebase.google.com/
    image_url: https://firebase.google.com/images/brand-guidelines/logo-logomark.png
  - name: Go
    web_url: https://golang.org/
    image_url: https://www.vectorlogo.zone/logos/golang/golang-icon.svg
  - name: Kotlin(android)
    web_url: https://kotlinlang.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/b/b5/Kotlin-logo.png
  
